### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by webmaster-jhon** [SaneMethod/CGWin#2]
Hi
I like your library. I just integrated to my page and getting error on `line# 30`:
`Uncaught TypeError: Cannot read property 'addEventListener' of undefined`

Please help me. 
Thanks

**Comment by webmaster-jhon** [comment]
I just replaced code at `line# 30` with:

```
$(document).delegate('.map-info-close', 'click', function(){
     this.close();
});
```

and it worked. Now getting error at `line# 42 & line# 56`. Following are the errors i get on both lines (respectively)

line# 42
`Uncaught TypeError: Cannot read property 'height' of undefined`

line# 56
`Uncaught TypeError: Cannot read property 'y' of null`

**Comment by SaneMethod** [comment]
Take a look at the example page at: http://sanemethod.github.io/CGWin/
The library expects a certain structure to the markup, as represented there (that was the cause of your first problem - an expected element wasn't present).
The cause of your second problem seems to be that you're not passing an icon definition for your marker in - again, take a look at the code on the example page, and you should be able to figure it out.

**Comment by webmaster-jhon** [comment]
Thanks for your help, those errors are gone. I have a `suggestion` to make this library a better option for other developers. I think info window should `behave like Google Maps default info window`. 

As of now, info window also `listens drag and click events`. For example if I click on custom info window and drag the map to left/right it works. I hope you understand my point.

**Comment by webmaster-jhon** [comment]
Any help about disabling **drag event** on custom info window?

**Comment by SaneMethod** [comment]
No, I don't want the custom info window to consume any more events then the absolute minimum by default - we want a more flexible window than the original, after all. If for your project you need to consume drag events on the custom info window, that should be as simple as adding appropriate listeners, and then preventing default actions/propagation as needed.

**Comment by webmaster-jhon** [comment]
I think there is a misunderstanding, let me make it clear. I was not asking about adding drag events to custom info window. As current info window already listens drag events. I just said that how to **prevent** drag events on custom info window?
